apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluence
  namespace: scheduler-plugins
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler
  template:
    metadata:
      labels:
        component: scheduler
    spec:
      serviceAccountName: scheduler-plugins
      containers:
        - image: quay.io/cmisale1/fluence-sidecar:latest
          imagePullPolicy: Always
          command:
          - /go/src/fluence/bin/server
          - --policy=lonode
          name: fluence-sidecar
        - image: quay.io/cmisale1/fluence:dev
          imagePullPolicy: Always
          command:
          - /bin/kube-scheduler
          - --config=/etc/kubernetes/scheduler-config.yaml
          - -v=9
          name: fluence
          resources:
            requests:
              cpu: '0.1'
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /etc/kubernetes
            name: scheduler-config
      hostNetwork: false
      hostPID: false
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
        
